baseURL = "https://fjord.jp/"
languageCode = "ja"
title = "Fjord, Inc"
theme = "fjord-2017"
disqusShortname = "fjord"
publishDir = "docs"
enableEmoji = true
googleAnalytics = "UA-2927688-6"
hasCJKLanguage = true
uglyURLs = true

[params]
  stylesheet = "assets/application.css"
  javascript = "assets/application.js"
  name = "Fjord, Inc"
  description = "株式会社フィヨルドはRailsを使った開発が得意なエンジニア1人とデザイナ1人の会社です。自社サービス運営、受託開発を行っています。"
  japanese_name = "株式会社フィヨルド"
  copyright = "Fjord, Inc"
  github = "https://github.com/fjordllc"
  amazon = "http://amzn.asia/emmGIQ8"
  amazon_id = "fjordllc-22"
  fb_app_id = "110692906285883"
  og_locale = "ja"
  og_image = "images/favicons/android-chrome-512x512.png"
  og_image_width = "512"
  opg_image_height = "512"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = false
